### ISSUE TITLE
[error]FEED_PRIVATE_ADDRESS_ERROR

### ISSUE THREAD

**Issue by hu-zhi-hang** [anyant/rssant#134]
#1 try https://www.bmpi.dev/index.xml

-202 FEED_PRIVATE_ADDRESS_ERROR when request 'https://www.bmpi.dev/index.xml'

The url is unable to connect or likely not contain feed, abort!

Not found any feed!

全部地址都报这个，进容器用 wget 能拉下来 xml
<img width="668" alt="image" src="https://user-images.githubusercontent.com/8455958/206884265-55e1cbd8-f2cc-4505-a84e-face7b7216d1.png">

**Comment by guyskk** [comment]
解决方案 https://github.com/anyant/rssant/issues/119

**Comment by raining1123** [comment]
我也遇到这个问题，是本地部署的，然后所有feed都失效。容器是走的bridge网络。
