### ISSUE TITLE
这个项目有病毒？

### ISSUE THREAD

**Issue by yak1990** [anyant/rssant#142]
1. git clone 文件有问题，扫描发现病毒
2. 下载的zip文件经扫描有病毒

**Comment by guyskk** [comment]
这么奇怪吗，提示哪个文件有病毒？用什么杀毒软件检测到的？可以截图看一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月20日(周三) 晚上9:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [anyant/rssant] 这个项目有病毒？ (Issue #142)




  
git clone 文件有问题，扫描发现病毒
 
下载的zip文件经扫描有病毒

**Comment by yak1990** [comment]
微软自带的杀毒软件

**Comment by guyskk** [comment]
复现了问题，看上去是测试数据集里面有一个链接是钓鱼网站的，去掉之后正常了。

<img width="599" alt="屏幕截图 2024-01-09 174616" src="https://github.com/anyant/rssant/assets/6367792/eb0d4f1b-58ee-4fe6-99a5-1ce0d55147cf">

非常感谢反馈！Fixed in https://github.com/anyant/rssant/commit/223b3809471b0754c70cd5d3d7dfb6167b8cca8e
