### ISSUE TITLE
列表标题支持图片显示

### ISSUE THREAD

**Issue by parkyang** [anyant/rssant#3]
真的太棒了！！！请问列表标题是否支持图片显示功能？

**Comment by guyskk** [comment]
感谢支持！！
标题应该没法显示图片吧，可以给一个截图或者例子吗？

**Comment by parkyang** [comment]
我添加了一个地址(https://www.cnbeta.com/)；
然后数据都正常加载了(非常棒)！
只是想在它得列表标题中看到文章内容得第一张图片(缩略图 )，因为很多时候缩略图就能让人感兴趣(有吸引力)！
**小小的提议**
![image](https://user-images.githubusercontent.com/2245630/76058721-1fc75600-5fb8-11ea-8130-c7123ce728d6.png)
![image](https://user-images.githubusercontent.com/2245630/76059282-649fbc80-5fb9-11ea-83e4-1d749297e87d.png)

**Comment by guyskk** [comment]
了解了，但是这个图放在标题里非常小，也看不清楚呀。
蚁阅的设计是让一屏显示更多资讯，阅读时就可以一目十行，所以也无法留一大块显示图片。

**Comment by guyskk** [comment]
@parkyang 蚁阅现已开始预售，可在蚁阅兑换页面输入你的GitHub ID直接兑换使用时长。再次感谢你的反馈建议~
后续开发计划见：https://rss.anyant.com/changelog?version=1.7.0

**Comment by guyskk** [comment]
@parkyang 蚁阅摘要现已支持显示图片，欢迎体验~

**Comment by emengweb** [comment]
希望支持列表显示模式的切换，默认只显示标题文字，建议增加显示摘要及图片的模式（类似于卡片模式），会增加文章吸引力，望采纳

**Comment by guyskk** [comment]
@emengweb 感谢建议，我加入开发计划中！
另送你一枚兑换码，输入你的GitHub ID即可兑换。

**Comment by emengweb** [comment]
谢谢！ 对啦，可以更新下docker么？目前docker里仍然是v1.7版的 ...

**Comment by guyskk** [comment]
@emengweb 收到，我周末更新一下。

**Comment by guyskk** [comment]
@emengweb Docker `guyskk/rssant:1.8.1` 已更新。

**Comment by emengweb** [comment]
> @emengweb Docker `guyskk/rssant:1.8.1` 已更新。

感谢，已经用上了，很赞！

**Comment by guyskk** [comment]
摘要已支持图片，标题图片应该没有必要了。
