### ISSUE TITLE
关于首屏

### ISSUE THREAD

**Issue by wasyddd** [anyant/rssant#74]
你好，开发者。我个人觉得底部分为已阅、未读、收藏 首页是类似于层级分类或许会高效一些 参考 reeder4。仅个人习惯。![Uploading 79774614...]()

**Comment by guyskk** [comment]
非常感谢建议！我最近正在构思蚁阅新的UI设计，你的反馈很有帮助，【高效】也是蚁阅的设计重点。reeder4确实很赞，值得借鉴。

**Comment by guyskk** [comment]
@wasyddd 蚁阅现已开始预售，可在蚁阅兑换页面输入你的GitHub ID直接兑换使用时长。再次感谢你的反馈建议~
后续开发计划见：https://rss.anyant.com/changelog?version=1.7.0
