### ISSUE TITLE
新版界面已上线，有什么想吐槽的吗？

### ISSUE THREAD

**Issue by guyskk** [anyant/rssant#76]
v1.4.0 重新设计了首页和订阅添加页面，走过路过欢迎吐槽和反馈~
点击下方表情按钮👍和👎参与投票，直接回复参与吐槽。

**Comment by lessmoe** [comment]
希望未来可以出一个按时间倒序的信息流的功能

**Comment by guyskk** [comment]
@lessmoe 非常感谢支持！我给你发了一封邮件，你可以看下，不知道是不是进了垃圾箱~

**Comment by Hello-XPH** [comment]
大佬有pc版本吗

**Comment by Hello-XPH** [comment]
还有就是，没有黑暗模式

**Comment by Hello-XPH** [comment]
大佬还需要加油

**Comment by guyskk** [comment]
@Hello-XPH 感谢支持，PC也支持的（直接浏览器打开使用），后续会优化PC界面。

**Comment by Hello-XPH** [comment]
不，不是wbe版本

**Comment by Hello-XPH** [comment]
pc本地的

**Comment by guyskk** [comment]
@Hello-XPH 目前只有web版本，以后可能会做成浏览器插件形式，单独维护PC端成本太高了。
另外Chrome上可以添加到桌面（需开启浏览器PWA功能），效果和桌面应用一样。参考：https://sspai.com/post/43499

**Comment by Hello-XPH** [comment]
哦，okok

**Comment by Hello-XPH** [comment]
谢谢

**Comment by yfnok** [comment]
rss今天安装了， 感谢，做的不错， 只是有个问题， 这个不能每个按照文件夹显示吗

**Comment by guyskk** [comment]
@yfnok 谢谢支持！分类分组功能还在规划中，敬请期待~

**Comment by yfnok** [comment]
> @yfnok 谢谢支持！分类分组功能还在规划中，敬请期待~

嗯，非常需要做个功能，要不然几十上百个订阅，太乱了。 谢谢大佬，东西不错

**Comment by psterman** [comment]
国产之光！分类能搞定就太好了！

**Comment by guyskk** [comment]
@lessmoe @Hello-XPH @yfnok @psterman 
蚁阅现已开始预售，可在蚁阅兑换页面输入你的GitHub ID直接兑换使用时长。再次感谢你的反馈建议~
后续开发计划见：https://rss.anyant.com/changelog?version=1.7.0
