### ISSUE TITLE
导入rss问题

### ISSUE THREAD

**Issue by Arrowzzzzzz** [anyant/rssant#77]
导入rss后，有些一时不能识别出来，但是能不能也在订阅页面上显示，可以放在一个未完全识别或者识别中模块里面，这样就能知道哪些没有识别出来

**Comment by guyskk** [comment]
这个会在订阅添加页面显示，红点表示有问题的订阅，参考最后一个截图：
![](https://raw.githubusercontent.com/anyant/rssant/master/docs/pictures/rssant-screenshot.png)

**Comment by Arrowzzzzzz** [comment]
不好意思没注意看，能看到红点，不过有功能，可以只看到红点的吗，应为这里面看到的不是全部rss订阅地址，在清理订阅里面能看到全部的rss订阅地址但是看不到未成功订阅的。
![深度截图_选择区域_20200516142654](https://user-images.githubusercontent.com/30648109/82112764-cb441200-9782-11ea-8cb5-b083cab7a260.png)

**Comment by guyskk** [comment]
逻辑是这样的，系统里已存在的订阅，会直接添加成功；其他的订阅需要几分钟时间查找和解析，这些会显示在订阅添加页面，状态也会更新在这。所以所有异常的订阅都会显示在这，手动看下哪些有红点就可以了（目前还没有排序和过滤功能）。

**Comment by Arrowzzzzzz** [comment]
好的，了解了，谢谢你

**Comment by guyskk** [comment]
不客气~  后续还有问题的话随时欢迎提issue~

**Comment by guyskk** [comment]
@Arrowzzzzzz 蚁阅现已开始预售，可在蚁阅兑换页面输入你的GitHub ID直接兑换使用时长。再次感谢你的反馈建议~

**Comment by Arrowzzzzzz** [comment]
好的，谢谢你
