### ISSUE TITLE
几条建议

### ISSUE THREAD

**Issue by laoxong** [anyant/rssant#79]
1. 倒叙
首先就是时间倒叙,旧的一般很少看了,现在还要使劲向下滑
2. 图片放大
文章中一些小图不方便看,可以添加个点击放大的功能
3. 图片的Lazyload
对于流量党来说有大用,以及关闭图片显示
4. 点击预览打开全部文章
5. 分组
这个对于订阅比较多的人来说作用很大

**Comment by guyskk** [comment]
非常感谢建议!
关于倒序，有个“看最新”按钮可以直接跳到最新一页，我也在考虑减少历史消息数量。
分组功能正在设计中，敬请期待。其他几个我先加到Todo list，都是很好的建议！

也欢迎加一下我weixin，方便后续沟通，账号是我的ID 🤝。

**Comment by laoxong** [comment]
> 非常感谢建议!
> 关于倒序，有个“看最新”按钮可以直接跳到最新一页，我也在考虑减少历史消息数量。
> 分组功能正在设计中，敬请期待。其他几个我先加到Todo list，都是很好的建议！
> 
> 也欢迎加一下我weixin，方便后续沟通，账号是我的ID 。

啊啊，我的微信因为用插件被封了，之后就没再注册，抱歉
有需要用tg@laoxong吧

**Comment by guyskk** [comment]
好的，没事，后续有需要 issues 和邮件也可以沟通。

**Comment by laoxong** [comment]
> 好的，没事，后续有需要 issues 和邮件也可以沟通。

BUG体制又找到了BUGxD
在文章页面刷新会导致订阅的文章变少,有时候会变没
视频:https://drive.google.com/file/d/1wijCtGFBG_ImiL8IG_mzyg9LbLyh1SCE/view?usp=sharing
邮箱的话就 i@moec.top 这个吧

**Comment by guyskk** [comment]
除倒序外其他均已实现。
