### ISSUE TITLE
传递全文

### ISSUE THREAD

**Issue by WhiCCX0** [anyant/rssant#80]
某些rrs源由于本身问题点开的文章只会显示标题，如果能有传递原文的功能那就太棒了。例图：
![Screenshot_20200819-022503](https://user-images.githubusercontent.com/47388635/90551155-82f22100-e1c3-11ea-9a11-ef980d8631ef.jpg)

**Comment by guyskk** [comment]
感谢反馈！
目前博客类的订阅支持抓取全文，但资讯类的还不行，因为资讯更新频繁，文章数量非常大。

**Comment by guyskk** [comment]
@WhiCCX0 蚁阅现已开始预售，可在蚁阅兑换页面输入你的GitHub ID直接兑换使用时长。再次感谢你的反馈建议~
