### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by mathgodess** [anyant/rssant#81]
可以隐藏已读（旧的太多看起来不是太美观）

**Comment by guyskk** [comment]
感谢反馈！
是指首页已读的(灰色)订阅太多吗？

**Comment by mathgodess** [comment]
是右边的标题列表

**Comment by mathgodess** [comment]
当然，不同的订阅能支持分类就更好了

**Comment by guyskk** [comment]
右边标题列表默认是隐藏已读的，可以截个图我看一下吗？
订阅分类在规划当中，敬请期待~

**Comment by mathgodess** [comment]
![捕获](https://user-images.githubusercontent.com/69997359/90843655-b8019d80-e394-11ea-9f87-01aa420732c8.JPG)

**Comment by guyskk** [comment]
@mathgodess 我验证了一下，如果打开时全部是已读，默认会显示最后一页(无滚动条)，不然页面就是空的。如果打开时有未读，就只显示未读。

**Comment by mathgodess** [comment]
好的，我知道了，谢谢开发者。

**Comment by guyskk** [comment]
不客气~

**Comment by guyskk** [comment]
@mathgodess 蚁阅现已开始预售，可在蚁阅兑换页面输入你的GitHub ID直接兑换使用时长。再次感谢你的反馈建议~
