### ISSUE TITLE
请问支持fever插件么，如果不支持以后会支持么

### ISSUE THREAD

**Issue by xiayasky** [anyant/rssant#82]
苹果全家桶，一直在用自建的ttrss，用reeder4阅读，想换成自建的蚂阅，但不知道支不支持fever插件

**Comment by guyskk** [comment]
感谢反馈！
蚁阅不支持fever插件，但有类似fever的功能，它会根据订阅更新频率决定内容展示在首页或合并为列表。
以后可能会考虑将不同订阅聚合，按热度排序，但目前来看，只订阅一两个资讯热榜可能更直接。



---原始邮件---
发件人: "xiayasky"<notifications@github.com&gt;
发送时间: 2020年9月18日(周五) 晚上11:40
收件人: "anyant/rssant"<rssant@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [anyant/rssant] 请问支持fever插件么，如果不支持以后会支持么 (#82)




 
苹果全家桶，一直在用自建的ttrss，用reeder4阅读，想换成自建的蚂阅，但不知道支不支持fever插件

**Comment by xiayasky** [comment]
> 感谢反馈！ 蚁阅不支持fever插件，但有类似fever的功能，它会根据订阅更新频率决定内容展示在首页或合并为列表。 以后可能会考虑将不同订阅聚合，按热度排序，但目前来看，只订阅一两个资讯热榜可能更直接。
> […](#)

感谢回复，那有没有什么办法支持reeder，或者以后会不会支持

**Comment by guyskk** [comment]
目前来看不会支持reeder，蚁阅是全平台阅读器，可以在 Mac 和 iOS 上像 App 一样使用（添加到主屏），我也在继续完善功能和用户体验。

**Comment by guyskk** [comment]
大致上，蚁阅的方向是会替换掉 ttrss，fever 和 reeder ，提供全平台开箱即用的功能和体验。

**Comment by guyskk** [comment]
@xiayasky 蚁阅现已开始预售，可在蚁阅兑换页面输入你的GitHub ID直接兑换使用时长。再次感谢你的反馈建议~
