### ISSUE TITLE
部分rss乱码

### ISSUE THREAD

**Issue by blue-bird1** [anyant/rssant#85]
`https://yufree.cn/cn/index.xml` 
我订阅了这个rss 然后
![image](https://user-images.githubusercontent.com/31133259/103486475-2709fb00-4e39-11eb-9c7b-49d8e0c8833a.png)

打开原页面是正常的

**Comment by guyskk** [comment]
感谢反馈，看上去博主昨天自己修复了，我把数据重刷了一下，现在是正常的了。

另外送你一枚兑换码，输入你的GitHub ID即可兑换。

**Comment by blue-bird1** [comment]
![image](https://user-images.githubusercontent.com/31133259/103675859-61030a80-4fbb-11eb-84e5-3805cf73bd8a.png)

**Comment by guyskk** [comment]
@blue-bird1 我也发现了，初步看是 feed response 不完整，导致了解码错误，可能也和 response 太大有关。

这个是 http 响应，最后面明显断了。结果也不稳定，时好时坏，我再深入分析一下。
![image](https://user-images.githubusercontent.com/6367792/103679704-25b70a80-4fc0-11eb-9d07-ac4db126ed6d.png)

**Comment by guyskk** [comment]
Python requests 也有 bug，没有检查 content-length 并丢弃错误数据
https://github.com/psf/requests/issues/4956

**Comment by guyskk** [comment]
已修复。参考: https://blog.petrzemek.net/2018/04/22/on-incomplete-http-reads-and-the-requests-library-in-python/
